"""
Configuration file for MIA System
Contains settings for Gemini, Grok, PDF generation, and file paths
"""

import os
from pathlib import Path

# Base directory
BASE_DIR = Path(__file__).parent.absolute()

# Directory paths
PROMPTS_DIR = BASE_DIR / "prompts"
ASSETS_DIR = BASE_DIR / "assets"
OUTPUTS_DIR = BASE_DIR / "outputs"
DATA_DIR = BASE_DIR / "data"
MODELS_DIR = BASE_DIR / "models"

# Create directories if they don't exist
for directory in [PROMPTS_DIR, ASSETS_DIR, OUTPUTS_DIR, DATA_DIR]:
    directory.mkdir(exist_ok=True)

# ============================================================================
# LLM CONFIGURATION
# ============================================================================

# Gemini 2.5 Flash Configuration (Vision Analysis & Cross-Validation)
GEMINI_CONFIG = {
    "model_name": "gemini-2.5-flash",  # Update to gemini-2.5-flash when available
    "api_key_env": "GEMINI_API_KEY",
    "temperature": 0.1,  # Low temperature for medical accuracy
    "top_p": 0.95,
    "top_k": 40,
    "max_output_tokens": 8192,
    "safety_settings": {
        "HARM_CATEGORY_HARASSMENT": "BLOCK_NONE",
        "HARM_CATEGORY_HATE_SPEECH": "BLOCK_NONE",
        "HARM_CATEGORY_SEXUALLY_EXPLICIT": "BLOCK_NONE",
        "HARM_CATEGORY_DANGEROUS_CONTENT": "BLOCK_NONE",
    }
}

# Groq Configuration (Report Generation & Safety Analysis)
GROQ_CONFIG = {
    "model_name": "llama-3.3-70b-versatile",  # or other Groq models
    "api_key_env": "GROQ_API_KEY",
    "base_url": "https://api.groq.com/openai/v1",
    "temperature": 0.2,  # Slightly higher for report generation
    "max_tokens": 8192,
    "top_p": 0.95,
}

# ============================================================================
# PROMPT FILE PATHS
# ============================================================================

PROMPTS = {
    # Gemini prompts
    "gemini_vision_analysis": PROMPTS_DIR / "gemini_vision_analysis_prompt.md",
    "gemini_cross_validation": PROMPTS_DIR / "gemini_cross_validation_prompt.md",
    "gemini_image_classification": PROMPTS_DIR / "gemini_image_classification_prompt.md",
    
    # Groq prompts
    "groq_report_generation": PROMPTS_DIR / "groq_report_generation_prompt.md",
    "groq_safety_analysis": PROMPTS_DIR / "groq_safety_analysis_prompt.md",
    "groq_cross_validation": PROMPTS_DIR / "groq_cross_validation_prompt.md",
}

# ============================================================================
# PDF GENERATION CONFIGURATION
# ============================================================================

PDF_CONFIG = {
    # Page settings
    "page_size": "A4",  # (210mm x 297mm)
    "page_width": 595.27,  # points (210mm)
    "page_height": 841.89,  # points (297mm)
    
    # Margins (in points, 1 inch = 72 points)
    "margin_top": 72,  # 1 inch
    "margin_bottom": 72,  # 1 inch
    "margin_left": 72,  # 1 inch
    "margin_right": 72,  # 1 inch
    
    # Fonts
    "fonts": {
        "title": {
            "family": "Helvetica-Bold",
            "size": 18
        },
        "heading": {
            "family": "Helvetica-Bold",
            "size": 14
        },
        "subheading": {
            "family": "Helvetica-Bold",
            "size": 12
        },
        "body": {
            "family": "Helvetica",
            "size": 10
        },
        "small": {
            "family": "Helvetica",
            "size": 8
        },
        "code": {
            "family": "Courier",
            "size": 9
        }
    },
    
    # Colors (RGB tuples, 0-1 scale)
    "colors": {
        "primary": (0.0, 0.3, 0.6),  # Dark blue
        "secondary": (0.4, 0.4, 0.4),  # Gray
        "accent": (0.0, 0.5, 0.8),  # Light blue
        "text": (0.0, 0.0, 0.0),  # Black
        "light_gray": (0.9, 0.9, 0.9),  # Light gray for backgrounds
        "white": (1.0, 1.0, 1.0),  # White
        "red": (0.8, 0.0, 0.0),  # Red for critical findings
        "orange": (1.0, 0.5, 0.0),  # Orange for warnings
        "green": (0.0, 0.6, 0.0),  # Green for normal
    },
    
    # Branding
    "branding": {
        "header_text": "MIA TEAM - AGENIX AI",
        "subtitle_text": "MEDICAL IMAGE ANALYSIS REPORT",
        "footer_text": "Generated by MIA Team - Agenix AI Medical Image Analysis",
        "watermark_text": "MIA TEAM",
        "watermark_opacity": 0.1,
    },
    
    # Logo settings
    "logo": {
        "path": ASSETS_DIR / "logo.png",  # User needs to provide this
        "width": 100,  # points
        "height": 100,  # points
        "watermark_width": 200,
        "watermark_height": 200,
    },
    
    # Image settings
    "image": {
        "max_width": 400,  # Maximum width for MRI images
        "max_height": 400,  # Maximum height for MRI images
        "quality": 85,  # JPEG quality (0-100)
    },
    
    # Layout settings
    "layout": {
        "line_spacing": 1.2,
        "paragraph_spacing": 12,
        "section_spacing": 20,
        "border_width": 1,
    }
}

# ============================================================================
# REPORT TEMPLATE SETTINGS
# ============================================================================

REPORT_TEMPLATE = {
    "page_1_sections": [
        "header",
        "patient_information",
        "study_information",
        "clinical_indication",
        "footer"
    ],
    "page_2_sections": [
        "header",
        "imaging_studies",
        "image_display",
        "technical_parameters",
        "footer"
    ],
    "page_3_sections": [
        "header",
        "findings",
        "impression",
        "differential_diagnosis",
        "clinical_correlation",
        "recommendations",
        "quality_assurance",
        "disclaimer",
        "footer"
    ]
}

# ============================================================================
# WORKFLOW SETTINGS
# ============================================================================

WORKFLOW_CONFIG = {
    "nodes": {
        "user_input": {
            "name": "User Input",
            "description": "Collect patient data and MRI image"
        },
        "validate": {
            "name": "Validation",
            "description": "Validate input data and image quality"
        },
        "vision": {
            "name": "Vision Analysis",
            "description": "Gemini analyzes MRI image",
            "llm": "gemini",
            "prompt": "gemini_vision_analysis"
        },
        "cross_validate": {
            "name": "Cross Validation",
            "description": "Gemini validates analysis results",
            "llm": "gemini",
            "prompt": "gemini_cross_validation"
        },
        "report": {
            "name": "Report Generation",
            "description": "Groq generates medical report",
            "llm": "groq",
            "prompt": "groq_report_generation"
        },
        "safety": {
            "name": "Safety Analysis",
            "description": "Groq performs safety validation",
            "llm": "groq",
            "prompt": "groq_safety_analysis"
        },
        "pdf_generation": {
            "name": "PDF Generation",
            "description": "Generate final PDF report"
        }
    },
    
    "flow": [
        "user_input",
        "validate",
        "vision",
        "cross_validate",
        "report",
        "safety",
        "pdf_generation"
    ]
}

# ============================================================================
# OUTPUT SETTINGS
# ============================================================================

OUTPUT_CONFIG = {
    "reports_dir": OUTPUTS_DIR / "reports",
    "images_dir": OUTPUTS_DIR / "images",
    "logs_dir": OUTPUTS_DIR / "logs",
    "temp_dir": OUTPUTS_DIR / "temp",
    
    "filename_format": "{patient_id}_{study_date}_{report_id}.pdf",
    "timestamp_format": "%Y%m%d_%H%M%S",
    "date_format": "%Y-%m-%d",
    "datetime_format": "%Y-%m-%d %H:%M:%S",
}

# Create output directories
for directory in OUTPUT_CONFIG.values():
    if isinstance(directory, Path):
        directory.mkdir(exist_ok=True, parents=True)

# ============================================================================
# VALIDATION SETTINGS
# ============================================================================

VALIDATION_CONFIG = {
    "patient": {
        "min_age": 0,
        "max_age": 150,
        "min_height_cm": 30,
        "max_height_cm": 300,
        "min_weight_kg": 1,
        "max_weight_kg": 500,
        "min_bmi": 10,
        "max_bmi": 100,
    },
    "image": {
        "supported_formats": [".jpg", ".jpeg", ".png", ".dcm", ".nii", ".nii.gz"],
        "max_file_size_mb": 100,
        "min_dimensions": (100, 100),
        "max_dimensions": (5000, 5000),
    }
}

# ============================================================================
# LOGGING SETTINGS
# ============================================================================

LOGGING_CONFIG = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "level": "INFO",
            "formatter": "standard",
            "stream": "ext://sys.stdout"
        },
        "file": {
            "class": "logging.FileHandler",
            "level": "DEBUG",
            "formatter": "standard",
            "filename": OUTPUT_CONFIG["logs_dir"] / "mia.log",
            "mode": "a"
        }
    },
    "loggers": {
        "": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": True
        }
    }
}

# ============================================================================
# SYSTEM INFORMATION
# ============================================================================

SYSTEM_INFO = {
    "name": "MIA - Medical Image Analysis",
    "version": "1.0.0",
    "description": "AI-powered medical image analysis system using Gemini and Grok",
    "organization": "Agenix AI - MIA Team",
    "contact": "mia-team@agenix.ai",
}
